<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FieldOps.Domain\FieldOps.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.1.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="C:\repo\dotnet\fieldops-dotnet\FieldOps.Application\DTOs\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\repo\dotnet\fieldops-dotnet\FieldOps.Application\DTOs\.editorconfig" />
  </ItemGroup>

</Project>
