version: '3.8'
services:
  db:
    image: postgres:17-alpine
    container_name: fieldops-postgres
    environment:
      POSTGRES_DB: fieldops_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: fieldops-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - db

  fieldops-api:
    build:
      context: ..
      dockerfile: FieldOps.Api/Dockerfile
    image: fieldops-api:local
    container_name: fieldops-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MIGRATE_ON_STARTUP: "true"
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=fieldops_dev;Username=postgres;Password=postgres"
    ports:
      - '5090:5090'
      - '7149:7149'
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres_data:
